server:
  port: 10000

spring:
  application:
    name: fancy-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:10100
      client:
        registration:
          fan:
            provider: fancy-authorization-server
            client-id: fancy-gateway
            client-secret: 123456
            authorization-grant-type: authorization_code
            scope: openid,profile,fan
        provider:
          fancy-authorization-server:
            issuer-uri: http://127.0.0.1:10100
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay
          routes:
            - id: fancy-iam
              uri: lb://fancy-iam
              predicates:
                - Path=/iam/**